### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by fa7ad** [hasinhayder/javascript-text-expander#4]
Completion doesn't seem to work if you don't use space before a word.

![2018-02-03-185159_1920x1080_scrot](https://user-images.githubusercontent.com/7447677/35767280-b0f1fbe2-0913-11e8-9946-0fdf3255c63f.png)

Guessing the issue has to do with words being split using only space, you can use the Regex `\W` metacharacter to get around it

**Comment by hasinhayder** [comment]
I will look into it, thanks :)
